config/routes.rb
Rails.application.routes.draw do

  get     '/login',     to: 'sessions#new',        as: 'new_login'
  post    '/login',     to: 'sessions#create',     as: 'login'
  delete  '/logout',    to: 'sessions#destroy',    as: 'logout'
  get     '/home',      to: "users#home",          as: "home"

  get '/about',         to: "landing_pages#about", as: "about"

  put 'requests/deny', as: 'deny'
  put 'requests/accept', as: 'accept'

  resources :albums
  resources :blogs
  resources :comments, only: [:show, :create, :edit, :update, :destroy]
  resources :conversations, only: [:index, :show, :create, :destroy]
  resources :events
  resources :friends, only: [:index, :create, :destroy]
  resources :messages, only: [:create, :destroy]
  resources :observations, only: [:show, :create, :edit, :update, :destroy]
  resources :photos, only: [:new, :show, :create, :edit, :update, :destroy]
  resources :posts, only: [:new, :show, :create, :edit, :update, :destroy]
  resources :requests, only: [:accept, :deny, :create, :destroy]
  resources :users

  root "landing_pages#about"
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  validates_presence_of :title, :description

  belongs_to :user
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.find(params[:id])
    authorize @blog
    @blogs = Blog.order(created_at: :desc)
    @posts = Post.order(created_at: :desc)
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
    @blog = Blog.find(params[:id])
    authorize @blog
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    authorize @blog
    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'New Blog successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { redirect_to :back, notice: "Blog was not created because #{@blog.errors.full_messages.each { |message| message } }"  }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { redirect_to :back, notice: "Blog was not updated because #{@blog.errors.full_messages.each { |message| message } }"  }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    authorize @blog
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :user_id, :description)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<div class="card big-padding">
  <%= form_for(@blog) do |f| %>
    <% if @blog.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

        <ul>
        <% @blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </div>
    <br />
    <div class="actions">
      <%= f.submit class: "btn light-green accent-4" %>
    </div>
  <% end %>
  <br />
</div>

app/views/blogs/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class='m12 m4 l4'>
      <h1 class="grey-text text-lighten-5 blogs center">Editing Blog</h1>
      <hr class="grey-text text-lighten-5">
      <br />
      <%= render 'form' %>

      <div class="card">
        <br />
        <%= link_to 'Show', @blog, class: "waves-effect waves-light btn light-green accent-4 side-margin-left" %>
        <%= link_to 'Back', @blog, class: "waves-effect waves-light btn light-green accent-4 side-margin-left" %>
        <br /><br />
      </div>
    </div>
  </div>
</div>

app/views/blogs/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='m12 m4 l4'>
      <h1 class="grey-text text-lighten-5 blogs center">Blogs</h1>
      <hr class="grey-text text-lighten-5">
      <br />
      <% if @current_user.blogs.empty? %>
        <div class="card big-padding">
          <h4 class="blue-text">You appear to not have a blog or made any posts yet...</h4>
          <%= link_to 'New Blog', new_blog_path, class: "waves-effect waves-light btn light-green accent-4" %>
          <br /><br />
        </div>
        <br />
      <% end %>

      <% unless @current_user.blogs.empty? %>
        <% @current_user.blogs.each do |blog| %>
          <%= link_to blog do %>
            <div>
              <ul class="collection">
                <li class="collection-item avatar">
                  <%= image_tag blog.user.image.url(:thumb), class: "circle" %>
                  <h2 class="bigger little-margin album arimo-font"><%= blog.title %></h2>
                  <div class="album">
                    <p><%= blog.description %></p>
                    <p><%= blog.user.full_name %></p>
                  </div>
                  <i class="material-icons secondary-content">format_align_left</i>
                </li>
              </ul>
            </div>
            <br />
          <% end %>
        <% end %>
      <% end %>
      <% @current_user.users_friends_blogs.each do |blog| %>
        <%= link_to blog do %>
          <div>
            <ul class="collection">
              <li class="collection-item avatar">
                <%= image_tag blog.user.image.url(:thumb), class: "circle"%>
                <h2 class="arimo-font bigger little-margin album"><%= blog.title %></h2>
                <div class="album">
                  <p><%= blog.description %></p>
                  <p><%= blog.user.full_name %></p>
                </div>
                <i class="material-icons secondary-content">format_align_left</i>
              </li>
            </ul>
          </div>
          <br />
        <% end %>
      <% end %>

      <% unless @current_user.blogs.empty? %>
        <div class="card">
          <br />
            <%= link_to 'New Blog', new_blog_path, class: "waves-effect waves-light btn light-green accent-4 side-margin-left" %>
          <br /><br />
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/blogs/new.html.erb
<div class='container'>
  <div class='row'>
    <div class='m12 m4 l4'>
      <h1 class="grey-text text-lighten-5 blogs center">New Blog</h1>
      <hr class="grey-text text-lighten-5">
      <br />
      <%= render 'form' %>

      <div class="card">
        <br />
        <%= link_to 'Back', blogs_path, class: "waves-effect waves-light btn light-green accent-4 side-margin-left" %>
        <br /><br />
      </div>
    </div>
  </div>
</div>

app/views/blogs/show.html.erb
  <br /><br />
  <div class='container'>
    <div class='row'>
      <div class='m12 m4 l4'>
          <h1 class="grey-text text-lighten-5 blogs center"><%= @blog.title %></h1>
          <hr class="grey-text text-lighten-5" />
          <h4 class="grey-text text-lighten-5 blogs center pacifico-font">
            <%= @blog.description %>
          </h4>

          <br />

        <% unless @blog.posts.empty? %>
          <% @blog.posts.each do |post| %>
            <div class="z-depth-1">
              <ul class="collection">
                <li class="collection-item">
                  <h4><%= link_to( "#{post.title}", post ) %></h4>
                  <p><%= link_to( "#{post.created_at.strftime("%B %e, %Y")}", post ) %></p><br/>
                  <p><%= link_to( "#{truncate(post.body, length: 350)}", post ) %></p>
                  <br />
                </li>
              </ul>
            </div>
            <br />
          <% end %>
        <% end %>

        <div class="card big padding">
          <br />
          <div class="row">
            <div class="col s12 m2 l2">
              <%= link_to 'Back', blogs_path, class: "waves-effect waves-light btn light-green accent-4 side-margin-left left little-margin-top" %>
            </div>
            <div class="col s12 m2 l2">
              <%= link_to 'New Post', new_post_path(:blog_id => @blog, :user_id => @blog), class: "waves-effect waves-light btn light-green accent-4 side-margin-left left little-margin-top" if @blog.user_id == @current_user.id %>
            </div>
            <div class="col s12 m2 l2">
              <%= link_to 'Edit Blog', edit_blog_path(@blog.id), class: "waves-effect waves-light btn light-green accent-4 side-margin-left left little-margin-top" if @blog.user_id == @current_user.id %>
            </div>
            <div class="col s12 m4 offset-m2 l3 offset-l3">
              <%= link_to 'Delete Blog', @blog, method: :delete, data: { confirm: 'Are you sure?' }, class: "waves-effect waves-light btn deep-orange accent-3 big-margin-right left little-margin-top side-margin-left" if @blog.user_id == @current_user.id %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>