config/routes.rb
Rails.application.routes.draw do

  get     '/login',     to: 'sessions#new',        as: 'new_login'
  post    '/login',     to: 'sessions#create',     as: 'login'
  delete  '/logout',    to: 'sessions#destroy',    as: 'logout'
  get     '/home',      to: "users#home",          as: "home"

  get '/about',         to: "landing_pages#about", as: "about"

  put 'requests/deny', as: 'deny'
  put 'requests/accept', as: 'accept'

  resources :albums
  resources :blogs
  resources :comments, only: [:show, :create, :edit, :update, :destroy]
  resources :conversations, only: [:index, :show, :create, :destroy]
  resources :events
  resources :friends, only: [:index, :create, :destroy]
  resources :messages, only: [:create, :destroy]
  resources :observations, only: [:show, :create, :edit, :update, :destroy]
  resources :photos, only: [:new, :show, :create, :edit, :update, :destroy]
  resources :posts, only: [:new, :show, :create, :edit, :update, :destroy]
  resources :requests, only: [:accept, :deny, :create, :destroy]
  resources :users

  root "landing_pages#about"
end

app/models/friend.rb
class Friend < ActiveRecord::Base
  has_one :conversation, dependent: :destroy
  belongs_to :friend_requester, :class_name => 'User', :foreign_key => 'friend_requester_id'
  belongs_to :friend_accepter, :class_name => 'User', :foreign_key => 'friend_accepter_id'
  has_many :events, dependent: :destroy
  has_many :messages, dependent: :destroy

  def each_friend
    "#{friend_requester.full_name} and #{friend_accepter.full_name}"
  end

  def friend_not_user(current_user)
    friend1 = self.friend_requester
    friend2 = self.friend_accepter
    if friend1 != current_user
      friend1.full_name
    else
      friend2.full_name
    end
  end

  def friend_is_user(current_user)
    friend1 = self.friend_requester
    friend2 = self.friend_accepter
    if friend1 == current_user
      friend1.full_name
    else
      friend2.full_name
    end
  end

  def other_user(current_user)
    friend1 = self.friend_requester
    friend2 = self.friend_accepter
    if friend1 == current_user
      friend2
    else
      friend1
    end
  end

  def is_user(current_user)
    friend1 = self.friend_requester
    friend2 = self.friend_accepter
    if friend1 != current_user
      friend2
    else
      friend1
    end
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user

  # GET /friends
  # GET /friends.json
  def index
    @friends = Friend.all
  end

  # POST /friends
  # POST /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: 'Friend was successfully created.' }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { redirect_to :back, notice: "Friend was not created because #{@friend.errors.full_messages.each { |message| message } }"  }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1
  # DELETE /friends/1.json
  def destroy
    @request = Request.where(user_id: [@friend.friend_requester_id, @friend.friend_accepter_id], requested_friend_id: [@friend.friend_requester_id, @friend.friend_accepter_id]).first
    @request.destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: 'Friend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friend_params
      params.require(:friend).permit(:friend_requester, :friend_accepter)
    end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='m12 m4 l4'>
      <h1 class="grey-text text-lighten-5 blogs center">Friends</h1>
      <hr class="grey-text text-lighten-5">
      <br />

      <% unless @current_user.friends.empty? %>
        <div class="card big-padding">
          <% @current_user.friends.each do |friend| %>
            <h5 class="arimo-font blue-text"><%= link_to "#{friend.other_user(@current_user).full_name}", user_path(friend.other_user(@current_user) ), class: "black-text" %></h5>
              <p>
                <%= link_to 'Create an event', new_event_path(:friend_id => friend.id), class: "waves-effect waves-light btn light-green accent-4" %>
                <%= link_to 'X', friend, method: :delete, data: { confirm: 'Are you sure?' }, class: "waves-effect waves-light btn deep-orange accent-3 right tooltipped", "data-position": "top", "data-delay": "50", "data-tooltip": "Disconnect" %>
              </p>
              <br /><hr>
          <% end %>
        </div>
      <% end %>
      <br />
      <div class="card">
        <br />
        <%= link_to "Find More Friends", users_path, class: "waves-effect waves-light btn light-green accent-4 side-margin-left" %>
        <br /><br />
      </div>
    </div>
  </div>
</div>