config/routes.rb
Rails.application.routes.draw do

  get     '/login',     to: 'sessions#new',        as: 'new_login'
  post    '/login',     to: 'sessions#create',     as: 'login'
  delete  '/logout',    to: 'sessions#destroy',    as: 'logout'
  get     '/home',      to: "users#home",          as: "home"

  get '/about',         to: "landing_pages#about", as: "about"

  put 'requests/deny', as: 'deny'
  put 'requests/accept', as: 'accept'

  resources :albums
  resources :blogs
  resources :comments, only: [:show, :create, :edit, :update, :destroy]
  resources :conversations, only: [:index, :show, :create, :destroy]
  resources :events
  resources :friends, only: [:index, :create, :destroy]
  resources :messages, only: [:create, :destroy]
  resources :observations, only: [:show, :create, :edit, :update, :destroy]
  resources :photos, only: [:new, :show, :create, :edit, :update, :destroy]
  resources :posts, only: [:new, :show, :create, :edit, :update, :destroy]
  resources :requests, only: [:accept, :deny, :create, :destroy]
  resources :users

  root "landing_pages#about"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_presence_of :first_name, :last_name, :username
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "150x150#" }, default_url: "/images/:style/missing.png", :storage => :s3, :bucket => "isles", :url =>':s3_domain_url',
  :path => ':class/:attachment/:id_partition/:style/:filename'
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  has_many :albums, dependent: :destroy
  has_many :blogs, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :friend_requested_friends, :class_name => 'Friend', :foreign_key => 'friend_requester_id', dependent: :destroy
  has_many :friend_accepted_friends, :class_name => 'Friend', :foreign_key => 'friend_accepter_id', dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :observations, dependent: :destroy
  has_many :photos, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :requests, dependent: :destroy
  has_many :requested_friends, through: :requests, dependent: :destroy
  has_many :reverse_requests, class_name: "Request", foreign_key: "requested_friend_id", dependent: :destroy
  has_many :reverse_requested_friends, through: :reverse_requests, source: :user, dependent: :destroy

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  #Request Methods

  def has_pending_friend_requests
    self.requests.any? do |request|
      [request.user_id].include?(self.id) && request.did_confirm == false
    end
  end

  def has_friend_requests
    self.reverse_requests.any? do |reverse_request|
      [reverse_request.requested_friend_id].include?(self.id) && reverse_request.did_confirm == false
    end
  end

  def friends
    self.friend_requested_friends + self.friend_accepted_friends
  end

  def is_friends(user)
    self.friends.any? do |friend|
      [friend.friend_requester_id, friend.friend_accepter_id].include?(user.id)
    end
  end

  def users_friends
    self.friends.map do |friend|
      friend.other_user(self)
    end
  end

  def users_friends_blogs
    self.users_friends.flat_map do |friend|
      friend.blogs
    end
  end

  def users_friends_albums
    self.users_friends.flat_map do |friend|
      friend.albums
    end
  end

  def image_url
    image.url(:thumb)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, except: [:new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = []
    if params[:search].present?
      parsed_search = params.fetch(:search, '').downcase.strip.split(' ')
      @users = User.where("
        lower(first_name) ILIKE ? OR
        lower(first_name) ILIKE ? OR
        lower(last_name)  ILIKE ? OR
        lower(last_name) ILIKE ?",
                            "%#{parsed_search.first}%", "%#{parsed_search.last}%",
                            "%#{parsed_search.first}%", "%#{parsed_search.last}%")
    end
  end

  def home
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    authorize @user
    @users = User.find(params[:id])
    @requests = User.find(params[:id]).requests
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    authorize @user
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to login_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    authorize @user
    session[:logged_in_users_id] = nil
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :username, :age, :city, :state, :twitter, :github, :linkedin, :phone_number, :birthday, :soundcloud, :facebook, :password, :image)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, html: { multipart: true } do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field center">
    <%= f.label :profile_image %><br>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :twitter %><br>
    <%= f.text_field :twitter %>
  </div>
  <div class="field">
    <%= f.label :github %><br>
    <%= f.text_field :github %>
  </div>
  <div class="field">
    <%= f.label :linkedin %><br>
    <%= f.text_field :linkedin %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br>
    <% if @user.birthday %>
      <%= f.text_field :birthday, class: "datepicker", value: @user.birthday.strftime("%B %e, %Y") %>
    <% else %>
      <%= f.text_field :birthday, class: "datepicker" %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :soundcloud %><br>
    <%= f.text_field :soundcloud %>
  </div>
  <div class="field">
    <%= f.label :facebook %><br>
    <%= f.text_field :facebook %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit class: "btn light-green accent-4" %>
  </div>
<% end %>
<br />

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class='m12 m4 l4'>
      <h1 class="grey-text text-lighten-5 blogs center">Edit User</h1>
      <hr class="grey-text text-lighten-5">
      <br />
      <div class="card big-padding">
        <%= render 'form' %>
        <div class="center">
          <%= link_to 'Show', @user, class: "waves-effect waves-light btn light-green accent-4" %>
          <%= link_to 'Back', :back, class: "waves-effect waves-light btn light-green accent-4" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/home.html.erb
<div class="intro z-depth-1 parallax-container no-margin-bottom">
  <div class="parallax"><%= image_tag "landing_page.jpg" %></div>
  <div class="container">
    <h1 class="grey-text text-lighten-5"><%= @current_user.full_name%></h1>
    <hr class="grey-text text-lighten-5">
    <h5 clas="grey lighten-4 grey-text text-darken-1">We're happy you're here!</h5>
  </div>
</div>

<div class="card no-margin home-height">
  <div class='container'>
    <div class='row'>
      <div class='m12 m4 l4'>
        <% if @current_user.has_friend_requests %>
          <br />
          <div class="card big-padding">
            <h2 class="no-margin">Friend Requests</h2>
            <hr>
            <ul>
              <% @current_user.reverse_requested_friends.each do |user| %>
                <% if !@current_user.is_friends(user) %>
                  <% if user.requests.where(requested_friend_id: @current_user.id).first.did_confirm == false %>
                    <li>
                    <br />
                    <h5><%= user.full_name %></h5>
                    <%= link_to "Accept", accept_path(user_id: user.id, requested_friend_id: @current_user.id), method: :PUT, class: "waves-effect waves-light btn light-green accent-4 left" %>
                    <%= link_to "Deny", deny_path(user_id: user.id, requested_friend_id: @current_user.id), method: :PUT, class: "waves-effect waves-light btn deep-orange accent-3 side-margin-left left" %>
                    <br />
                    </li>
                  <% end %>
                <% end %>
              <% end %>
            </ul>
          </div>
        <% end %>

        <% if @current_user.albums.empty? && !@current_user.blogs.empty? %>
          <div>
            <h3 class="center-text">You don't have any photo albums yet, would you like to upload some photos to share with your friends?</h3>
            <p class="center-text"><%= link_to "Start sharing", new_album_path, class: "waves-effect waves-light btn light-green accent-4" %></p>
          </div>
          <br />
          <div class="row">
            <div class="col s12 m12 offset-l2 l8">
              <div class="card center">
                <% unless @current_user.blogs.empty? %>
                  <h5>Blogs</h5>
                    <% @current_user.blogs.each do |blog| %>
                      <hr>
                      <h5 class="pacifico-font"><%= link_to( "#{blog.title}", blog ) %></h5>
                    <% end %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>

        <% if @current_user.blogs.empty? && !@current_user.albums.empty? %>
          <div>
            <h3 class="center-text">You haven't written anything yet, would you like to start a blog?</h3>
            <p class="center-text"><%= link_to "Start writing", new_blog_path, class: "waves-effect waves-light btn light-green accent-4" %></p>
          </div>
          <br />
          <div class="row">
            <div class="col s12 m12 offset-l2 l8">
              <div class="card center">
                <% unless @current_user.albums.empty? %>
                  <h5>Albums</h5>
                    <% @current_user.albums.each do |album| %>
                      <hr>
                      <h5 class="pacifico-font"><%= link_to( "#{album.title}", album ) %></h5>
                    <% end %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>

        <% if @current_user.blogs.empty? && @current_user.albums.empty? %>
          <div>
            <h3 class="center-text">You haven't written anything yet, would you like to start a blog?</h3>
            <p class="center-text"><%= link_to "Start writing", new_blog_path, class: "waves-effect waves-light btn light-green accent-4" %></p>
          </div>
          <br />
          <div>
            <h3 class="center-text"> Or...</h3>
          </div>
          <br />
          <div>
            <h3 class="center-text">You don't have any photo albums yet, would you like to upload some photos to share with your friends?</h3>
            <p class="center-text"><%= link_to "Start sharing", new_album_path, class: "waves-effect waves-light btn light-green accent-4" %></p>
          </div>
          <br />
        <% end %>

        <% if !@current_user.blogs.empty? && !@current_user.albums.empty? %>
          <br />
          <div class="row">
            <div class="col s12 m6 l6">
              <div class="card center">
                <% unless @current_user.blogs.empty? %>
                  <h5>Blogs</h5>
                    <% @current_user.blogs.each do |blog| %>
                      <hr>
                      <h5 class="pacifico-font"><%= link_to( "#{blog.title}", blog ) %></h5>
                    <% end %>
                <% end %>
              </div>
            </div>
            <div class="col s12 m6 l6">
              <div class="card center">
                <% unless @current_user.albums.empty? %>
                <h5>Photos</h5>
                  <% @current_user.albums.each do |album| %>
                      <hr>
                      <h5 class="pacifico-font"><%= link_to "#{album.title}", album %></h5>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>

        <% if @current_user.has_pending_friend_requests %>
          <div class="card big-padding">
            <h2 class="no-margin">Pending Friend Requests</h2>
            <hr>
            <ul>
              <% @current_user.requests.each do |request| %>
                <% unless request.did_confirm == true %>
                  <li>
                  <br />
                    <h5><%= request.requested_friend.full_name %></h5>
                    <%= link_to "Cancel", request, method: :DELETE, class: "waves-effect waves-light btn light-green accent-4" %>
                  </li>
                <% end %>
              <% end %>
            </ul>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='m12 m4 l4'>
      <h1 class="grey-text text-lighten-5 blogs center">Search Users</h1>
      <hr class="grey-text text-lighten-5">
      <br />
      <div class="card search">
        <%= form_tag users_path, :method => 'get' do %>
          <p>
          <%= text_field_tag :search, params[:search], placeholder: "Search Users" %>
          <%= submit_tag "Search", :name => nil, class: "btn light-green accent-4" %>
          </p>
        <% end %>

        <br />
        <% unless @users.empty? || @users.first == @current_user %>
          <table>
            <thead>
              <tr>
                <th>First name</th>
                <th>Last name</th>
                <th>Age</th>
                <th>City</th>
                <th>State</th>
                <th></th>
              </tr>
            </thead>

            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <% unless user == @current_user%>
                    <td><%= link_to "#{user.first_name}", user %></td>
                    <td><%= link_to "#{user.last_name}", user %></td>
                    <td><%= user.age unless user.age.nil? || user.age.blank? %></td>
                    <td><%= user.city unless user.city.nil? || user.city.empty?%></td>
                    <td><%= user.state unless user.state.nil? || user.state.empty?%></td>
                    <td class="center"><%= link_to( "Add Friend", requests_path(:requested_friend_id => user), :method => :post, class: "waves-effect waves-light btn light-green accent-4") if
                @current_user.requests.where(:requested_friend_id => user.id).where(:user_id => @current_user.id).empty? && !user.requests.where(requested_friend_id: @current_user.id).exists? %></td>
                  <% end %>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<br />
<div class='container'>
  <div class='row'>
    <div class='m12 m4 l4'>
      <h1 class="grey-text text-lighten-5 blogs center">Welcome!</h1>
      <hr class="grey-text text-lighten-5">
      <br />
      <div class="card big-padding">
        <%= render 'form' %>
        <div>
          <%= link_to 'Back', :back, class: "waves-effect waves-light btn light-green accent-4" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container about">
  <br />
  <div class="row">
    <div class="col s12 m4 l4">
      <div class="card">
        <div class="card-content center">
          <%= image_tag @user.image.url(:thumb), class: "circle" unless @user.image.url(:medium) == "/images/medium/missing.png" %>
        </div>
        <div class="card-action">
        <p class="bigger center-text"><%= @user.full_name %></p>
        </div>
      </div>
    </div>
    <div class="col s12 m4 l4">
      <div class="card center">
        <% unless @user.albums.empty? %>
        <h5>Photos</h5>
          <% @user.albums.each do |album| %>
              <hr>
              <h5 class="pacifico-font"><%= link_to "#{album.title}", album %></h5>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="col s12 m4 l4">
      <div class="card center">
        <% unless @user.blogs.empty? %>
          <h5>Blogs</h5>
            <% @user.blogs.each do |blog| %>
              <hr>
              <h5 class="pacifico-font"><%= link_to( "#{blog.title}", blog ) %></h5>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class='container'>
  <div class='row'>
    <div class='m12 m4 l4'>
    <br />

      <div class="card big-padding">

        <p>
          <strong>Email:</strong>
          <%= @user.email %>
        </p>

        <% unless @user.age.blank? || @user.age.nil? %>
          <p>
            <strong>Age:</strong>
            <%= @user.age %>
          </p>
        <% end %>

        <% unless @user.city.blank? || @user.city.nil? %>
          <p>
            <strong>City:</strong>
            <%= @user.city %>
          </p>
        <% end %>

        <% unless @user.state.blank? || @user.state.nil? %>
          <p>
            <strong>State:</strong>
            <%= @user.state %>
          </p>
        <% end %>

        <% unless @user.twitter.blank? || @user.twitter.nil? %>
          <p>
            <strong>Twitter:</strong>
            <%= @user.twitter %>
          </p>
        <% end %>

        <% unless @user.github.blank? || @user.github.nil? %>
          <p>
            <strong>Github:</strong>
            <%= @user.github %>
          </p>
        <% end %>

        <% unless @user.linkedin.blank? || @user.linkedin.nil? %>
          <p>
            <strong>Linkedin:</strong>
            <%= @user.linkedin %>
          </p>
        <% end %>

        <% unless @user.phone_number.blank? || @user.phone_number.nil? %>
          <p>
            <strong>Phone number:</strong>
            <%= @user.phone_number %>
          </p>
        <% end %>

        <% unless @user.birthday.blank? || @user.birthday.nil? %>
          <p>
            <strong>Birthday:</strong>
            <%= @user.birthday.strftime("%B %e, %Y") %>
          </p>
        <% end %>

        <% unless @user.soundcloud.blank? || @user.soundcloud.nil? %>
          <p>
            <strong>Soundcloud:</strong>
            <%= @user.soundcloud %>
          </p>
        <% end %>

        <% unless @user.facebook.blank? || @user.facebook.nil? %>
          <p>
            <strong>Facebook:</strong>
            <%= @user.facebook %>
          </p>
        <% end %>
      </div>

      <div class="card big-padding">
        <div class="row">
          <div class="col s12 m2 l2">
            <%= link_to 'Back', :back, class: "waves-effect waves-light btn light-green accent-4  left little-margin-top side-margin-left" %>
          </div>
          <div class="col s12 m2 l2">
            <%= link_to 'Edit', edit_user_path(@user), class: "waves-effect waves-light btn light-green accent-4 left little-margin-top side-margin-left" if @current_user == @user %>
          </div>
          <div class="col s12 m1 offset-m5 l1 offset-l5">
            <%= link_to 'Delete Account', @user, method: :delete, data: { confirm: 'Are you sure?' }, class: "waves-effect waves-light btn deep-orange accent-3 big-margin-right left little-margin-top side-margin-left side-margin-right" if @current_user == @user %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>