config/routes.rb
Rails.application.routes.draw do

  get     '/login',     to: 'sessions#new',        as: 'new_login'
  post    '/login',     to: 'sessions#create',     as: 'login'
  delete  '/logout',    to: 'sessions#destroy',    as: 'logout'
  get     '/home',      to: "users#home",          as: "home"

  get '/about',         to: "landing_pages#about", as: "about"

  put 'requests/deny', as: 'deny'
  put 'requests/accept', as: 'accept'

  resources :albums
  resources :blogs
  resources :comments, only: [:show, :create, :edit, :update, :destroy]
  resources :conversations, only: [:index, :show, :create, :destroy]
  resources :events
  resources :friends, only: [:index, :create, :destroy]
  resources :messages, only: [:create, :destroy]
  resources :observations, only: [:show, :create, :edit, :update, :destroy]
  resources :photos, only: [:new, :show, :create, :edit, :update, :destroy]
  resources :posts, only: [:new, :show, :create, :edit, :update, :destroy]
  resources :requests, only: [:accept, :deny, :create, :destroy]
  resources :users

  root "landing_pages#about"
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates_presence_of :dateof, :occasion, :description
  belongs_to :friend
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user

  # GET /events
  # GET /events.json
  def index
    @user = current_user
    @friends = @user.friends
    @events = Event.order(friend_id: :asc, dateof: :asc, created_at: :asc)
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to events_path, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:occasion, :description, :dateof, :milestone, :friend_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="card big-padding">
  <%= form_for(@event) do |f| %>
    <% if @event.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

        <ul>
        <% @event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :occasion %><br>
      <%= f.text_field :occasion %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </div>
    <div class="field">
    <%= f.label :dateof %><br>
    <% if @event.dateof %>
      <%= f.text_field :dateof, class: "datepicker", value: @event.dateof.strftime("%B %e, %Y") %>
    <% else %>
      <%= f.text_field :dateof, class: "datepicker" %>
    <% end %>
  </div>
    <br />
    <div class="field">
      <%= f.hidden_field :friend_id, value: params[:friend_id] %>
    </div>
    <div class="actions">
      <%= f.submit class: "btn light-green accent-4"  %>
    </div>
  <% end %>
</div>

app/views/events/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class='m12 m4 l4'>
      <h1 class="center grey-text text-lighten-5 blogs">Editing Event</h1>
      <hr class="grey-text text-lighten-5">
      <br />
      <%= render 'form' %>

      <%= link_to 'Show', @event, class: "waves-effect waves-light btn light-green accent-4"  %>
      <%= link_to 'Back', events_path, class: "waves-effect waves-light btn light-green accent-4"  %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='m12 m4 l4'>
      <h1 class="grey-text text-lighten-5 blogs center">Timelines</h1>
      <hr class="grey-text text-lighten-5">
      <br />
      <% @friends.each do |friend| %>
        <% unless friend.events.empty? %>
          <div class="card big-padding">
            <h3 class="little-margin-top blue-text"><%= link_to "#{friend.friend_not_user(@current_user)}", friend.other_user(@current_user) %></h3>
          </div>

          <% friend.events.each do |event| %>
            <div class="card big-padding">
              <h4><%= event.dateof.strftime("%B %e, %Y") %></h4>
              <h5><%= event.occasion %></h5>
              <p class="decent-margin-bottom"><%= event.description %></p>
              <div class="row">
                <div class="col s12 m3 l2">
                  <%= link_to "Create Event", new_event_path(:friend_id => friend.id), class: "waves-effect waves-light btn light-green accent-4 decent-margin-left left little-margin-top big-margin-right" %>
                </div>
                <div class="col s12 m3 l2">
                  <%= link_to 'Show', event, class: "waves-effect waves-light btn light-green accent-4 decent-margin-left left little-margin-top" %>
                </div>
                <div class="col s12 m1 l2">
                  <%= link_to 'Edit', edit_event_path(event, :friend_id => event.friend_id), class: "waves-effect waves-light btn light-green accent-4 decent-margin-left left little-margin-top" %>
                </div>
                <div class="col s12 m3 offset-m2 l3 offset-l3">
                  <%= link_to 'Delete Event', event, method: :delete, data: { confirm: 'Are you sure?' }, class: "waves-effect waves-light btn deep-orange accent-3 big-margin-right left little-margin-top decent-margin-left" %>
                </div>
              </div>
            </div>
          <% end %>

          <br />
        <% end %>
      <% end %>
      <% @friends.each do |friend| %>
        <% if friend.events.empty? %>
          <div class="card big-padding">
            <h4 class="little-margin-top blue-text">You don't have any events with <%= "#{friend.friend_not_user(@current_user)}"%> yet...</h4>
            <p><%= link_to "Create An Event!", new_event_path(:friend_id => friend.id), class: "waves-effect waves-light btn light-green accent-4" %></p>
          </div>
          <br />
        <% end %>
      <% end %>
      <br>

    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class='container'>
  <div class='row'>
    <div class='m12 m4 l4'>
      <h1 class="grey-text text-lighten-5 blogs center">New Event</h1>
      <hr class="grey-text text-lighten-5">
      <br />
      <%= render 'form' %>

      <div class="card">
        <br />
        <%= link_to 'Back', events_path, class: "waves-effect waves-light btn light-green accent-4 side-margin-left" %>
        <br /><br />
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='m12 m4 l4'>
      <h1 class="center grey-text text-lighten-5 blogs"><%= @event.occasion %></h1>
      <h3 class="center grey-text text-lighten-5 blogs">happened on <%= @event.dateof.strftime("%B %e, %Y") %>, with <%= @event.friend.other_user(@current_user).full_name %></h3>
      <hr class="grey-text text-lighten-5">
      <br />

      <div class="card big-padding">
        <p>
          <%= @event.description %>
        </p>
      </div>

      <div class="card">
        <br />
        <%= link_to 'Back', events_path, class: "waves-effect waves-light btn light-green accent-4 side-margin-left"  %>
        <%= link_to 'Edit', edit_event_path(@event, :friend_id => @event.friend_id), class: "waves-effect waves-light btn light-green accent-4 side-margin-left"  %>
        <br /><br />
      </div>
    </div>
  </div>
</div>